var bindItems = {
	"Movement": {
		"binditem001": {
			"name": "Forward",
			"command": "+forward",
			"description": "",
			"iconlink": "forward.png",
		},
		"binditem002": {
			"name": "Backpedal",
			"command": "+back",
			"description": "",
			"iconlink": "backpedal.png",
		},
		"binditem003": {
			"name": "Move Left",
			"command": "+moveleft",
			"description": "",
			"iconlink": "moveleft.png",
		},
		"binditem004": {
			"name": "Move Right",
			"command": "+moveright",
			"description": "",
			"iconlink": "moveright.png",
		},
		"binditem005": {
			"name": "Jump",
			"command": "+moveup",
			"description": "",
			"iconlink": "jump.png",
		},
		"binditem006": {
			"name": "Crouch",
			"command": "+movedown",
			"description": "",
			"iconlink": "crouch.png",
		},
		"binditem007": {
			"name": "Silent Walk",
			"command": "+speed",
			"description": "",
			"iconlink": "silentwalk.png",
		},
		"binditem008": {
			"name": "Center View",
			"command": "centerview",
			"description": "",
			"iconlink": "centerview.png",
		},
	},
	"Actions": {
		"binditem009": {
			"name": "Shoot",
			"command": "+attack",
			"description": "",
			"iconlink": "shoot.png",
		},
		"binditem010": {
			"name": "Toggle Weapon",
			"command": "weapon toggle",
			"description": "",
			"iconlink": "toggleweapon.png",
		},
		"binditem011": {
			"name": "Next Weapon",
			"command": "weapnext",
			"description": "",
			"iconlink": "nextweapon.png",
		},
		"binditem012": {
			"name": "Previous Weapon",
			"command": "weapprev",
			"description": "",
			"iconlink": "previousweapon.png",
		},
		"binditem013": {
			"name": "Zoom",
			"command": "+zoom",
			"description": "",
			"iconlink": "zoom.png",
		},
		"binditem014": {
			"name": "Use Item",
			"command": "+button2",
			"description": "",
			"iconlink": "useitem.png",
		},
		"binditem015": {
			"name": "Scoreboard",
			"command": "+scores",
			"description": "",
			"iconlink": "scoreboard.png",
		},
		"binditem016": {
			"name": "Ready Up",
			"command": "readyup",
			"description": "",
			"iconlink": "readyup.png",
		},
		"binditem017": {
			"name": "Taunt",
			"command": "+button3",
			"description": "",
			"iconlink": "taunt.png",
		},
		"binditem018": {
			"name": "Drop Flag",
			"command": "dropflag",
			"description": "",
			"iconlink": "dropflag.png",
		},
		"binditem019": {
			"name": "Drop Powerup",
			"command": "droppowerup",
			"description": "",
			"iconlink": "droppowerup.png",
		},
		"binditem020": {
			"name": "Drop Weapon",
			"command": "dropweapon",
			"description": "",
			"iconlink": "dropweapon.png",
		},
		"binditem021": {
			"name": "Accuracy",
			"command": "+acc",
			"description": "Shows an Accuracy-Menu with Percent Values of every Weapon.",
			"iconlink": "accuracy.png",
		},
		"binditem022": {
			"name": "Self Kill",
			"command": "kill",
			"description": "",
			"iconlink": "selfkill.png",
		},
		"binditem023": {
			"name": "Screenshot",
			"command": "screenshotJPEG",
			"description": "",
			"iconlink": "screenshot.png",
		},
	},
	"Weapons": {
		"binditem024": {
			"name": "Gauntlet",
			"command": "weapon 1",
			"description": "",
			"iconlink": "gauntlet.png",
		},
		"binditem025": {
			"name": "Machine Gun",
			"command": "weapon 2",
			"description": "",
			"iconlink": "machinegun.png",
		},
		"binditem026": {
			"name": "Shotgun",
			"command": "weapon 3",
			"description": "",
			"iconlink": "shotgun.png",
		},
		"binditem027": {
			"name": "Grenade Launcher",
			"command": "weapon 4",
			"description": "",
			"iconlink": "grenadelauncher.png",
		},
		"binditem028": {
			"name": "Rocket Launcher",
			"command": "weapon 5",
			"description": "",
			"iconlink": "rocketlauncher.png",
		},
		"binditem029": {
			"name": "Lightning Gun",
			"command": "weapon 6",
			"description": "",
			"iconlink": "lightninggun.png",
		},
		"binditem030": {
			"name": "Rail Gun",
			"command": "weapon 7",
			"description": "",
			"iconlink": "railgun.png",
		},
		"binditem031": {
			"name": "Plasma Gun",
			"command": "weapon 8",
			"description": "",
			"iconlink": "plasmagun.png",
		},
		"binditem032": {
			"name": "BFG",
			"command": "weapon 9",
			"description": "",
			"iconlink": "bfg.png",
		},
		"binditem033": {
			"name": "Grappling Hook",
			"command": "weapon 10",
			"description": "",
			"iconlink": "grapplinghook.png",
		},
		"binditem034": {
			"name": "Nail Gun",
			"command": "weapon 11",
			"description": "",
			"iconlink": "nailgun.png",
		},
		"binditem035": {
			"name": "Proximity Mine Launcher",
			"command": "weapon 12",
			"description": "",
			"iconlink": "proximityminelauncher.png",
		},
		"binditem036": {
			"name": "Chain Gun",
			"command": "weapon 13",
			"description": "",
			"iconlink": "chaingun.png",
		},
		"binditem037": {
			"name": "Heavy Machine Gun",
			"command": "weapon 14",
			"description": "",
			"iconlink": "heavymachinegun.png",
		},
	},
	"Chat": {
		"binditem038": {
			"name": "Talk",
			"command": "messagemode",
			"description": "",
			"iconlink": "talk.png",
		},
		"binditem039": {
			"name": "Team Talk",
			"command": "messagemode2",
			"description": "",
			"iconlink": "teamtalk.png",
		},
		"binditem040": {
			"name": "Talk To Target",
			"command": "messagemode3",
			"description": "",
			"iconlink": "talktotarget.png",
		},
		"binditem041": {
			"name": "Talk To Attacker",
			"command": "messagemode4",
			"description": "",
			"iconlink": "talktoattacker.png",
		},
		"binditem042": {
			"name": "Chat History",
			"command": "+chat",
			"description": "",
			"iconlink": "chathistory.png",
		},
		"binditem043": {
			"name": "Reply To Friend",
			"command": "messagemode5",
			"description": "",
			"iconlink": "replytofriend.png",
		},
	},
	"Additional": {
		"binditem044": {
			"name": "Turn Left",
			"command": "+left",
			"description": "",
			"iconlink": "left.png",
		},
		"binditem045": {
			"name": "Turn Right",
			"command": "+right",
			"description": "",
			"iconlink": "right.png",
		},
		"binditem046": {
			"name": "Look Up",
			"command": "+lookup",
			"description": "",
			"iconlink": "lookup.png",
		},
		"binditem047": {
			"name": "Look Down",
			"command": "+lookdown",
			"description": "",
			"iconlink": "lookdown.png",
		},
		"binditem048": {
			"name": "Vote Yes",
			"command": "vote yes",
			"description": "",
			"iconlink": "voteyes.png",
		},
		"binditem049": {
			"name": "Vote No",
			"command": "vote no",
			"description": "",
			"iconlink": "voteno.png",
		},
	},
};